const ApplicationName = 'Fetion';
const ApplicationVersion = '1.0.0.1';
const UserId = "95t37897vjco6jnn9379345tptevyd";
const SettingId = '22sad1df2rsdf1asda23';
const NickNamePrefix = ApplicationName + " " + "User";
const DefaultHostName = "Unknown";
const DataBaseName = 'Fetion';
const DataBaseVersion = 17;
const FontFamilyName = 'AlibabaPuHuiTi';
const double SecondBarWidth = 240;
const int DefaultFontSize = 13;
const int DisplayMaxMessages = 99;
const int DisplayMinMessages = 0;
const double FontSizeMax = 18;
const double FontSizeMin = 10;
const String DefaultMaskCode = '255.255.255.250';
const String OpenSourceAddr = 'https://github.com/wu-yiqiang/fetion';
const String IssuesAddr = 'https://github.com/wu-yiqiang/fetion/issues';
const String DefaultPassword = '1234@Abcd';

class ChatType {
  static const ME = 'me';
  static const OTHER = 'other';
}

class LanguageMap {
  static const ENGLISH = 'English';
  static const SIMPLECHINESE = '简体中文';
}

class LanguageEnTypeMap {
  static const TYPE = 'en';
  static const COUNTRY = 'US';
}

class LanguageZhTypeMap {
  static const TYPE = 'zh';
  static const COUNTRY = 'CN';
}

const Languages = [
  {
    'value': LanguageMap.ENGLISH,
    'type': LanguageEnTypeMap.TYPE,
    'country': LanguageEnTypeMap.COUNTRY,
  },
  {
    'value': LanguageMap.SIMPLECHINESE,
    'type': LanguageZhTypeMap.TYPE,
    'country': LanguageZhTypeMap.COUNTRY,
  },
];

class MsgType {
  static const TEXT = 0;
  static const IMAGE = 1;
  static const FILE = 2;
}
class MsgStatus {
  static const SENDING = 0;
  static const SENDED = 1;
  static const READED = 2;
  static const WITHDRAW = 3;
}
class ThemeModeMap {
  // static const SYSTEM = 'System';
  static const DARK = 'Dark';
  static const LIGHT = 'Light';
}

const ThemeModes = [ThemeModeMap.LIGHT, ThemeModeMap.DARK];

const DefaultAvatar =
    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wEEEABQAFAAUABQAFUAUABaAGQAZABaAH0AhwB4AIcAfQC5AKoAmwCbAKoAuQEYAMgA1wDIANcAyAEYAakBCQE2AQkBCQE2AQkBqQF3AccBcgFZAXIBxwF3AqMCEgHWAdYCEgKjAwwCjwJsAo8DDAOxA00DTQOxBKYEagSmBhMGEwgqEQBQAFAAUABQAFUAUABaAGQAZABaAH0AhwB4AIcAfQC5AKoAmwCbAKoAuQEYAMgA1wDIANcAyAEYAakBCQE2AQkBCQE2AQkBqQF3AccBcgFZAXIBxwF3AqMCEgHWAdYCEgKjAwwCjwJsAo8DDAOxA00DTQOxBKYEagSmBhMGEwgq/8IAEQgBwAHAAwEiAAIRAQMRAf/EACsAAQEBAQEBAAAAAAAAAAAAAAAEAwIBBQEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcSlGOQ98B74NdpB9BFUdgAAAAAAAAAAAAAAAAAAAAZ+xA9PNKNDDvQZ8biPP6GZG98LNPn2nYAAAAAAAAAAAAAAAAAABmTcB7bzoAAAAcxX5kffA+gz0AAAAAAAAAAAAAAAAAAEtUJz3xSbgAAAAAi4pmNqobgAAAAAAAAAAAAAAAAAB8/6HzxXJWagAAAAAykrkH0Pn/QAAAAAAAAAAAAAAAAAAEN0pjRP2WgAAAAAnn74OrpagAAAAAAAAAAAAAAAAABnoPntMyvWCw7AAAAy6jPDQo0AAAAAAAAAAAAAAAAAAADmK/gi9eFevz+i5P0bMeSjKbk98ei3zsAAAAAAAAAAAAAAAAAAAAE5rEAAAAC2IfQT0AAAAAAAAAAAAAAAAAAADxEe8AbUk+ug89B56M8qR89fMY98C/wBhtPQAAAAAAAAAAAAAAAACcy4BV7qAAAAAAZSfQxJe+B9BPQAAAAAAAAAAAAAAAAeQUTjbG89AAAAAAABLjfAL4KCgAAAAAAAAAAAAAAA8IuQ3pz0AAAAAAAAE1OZH1yPoPPQAAAAAAAAAAAAABnpkSAv9AAAAAAAAB56Pngs0y1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/EACcQAAIBAwMDBAMBAAAAAAAAAAECAwAQERIxUDAyQBMgIVEiQUKQ/9oACAEBAAE/AP8AShplFGZ6Lsd2Nw7DZjQmelmU8e7hKeRn6KSMlI4fjJJAlEknJusTtQgFeileilGAU0TrcEg5FRyB+Kdwgokk5NlUscCkiVfe8StTKVODYEg5FI4ccTI+prKpY4FKoUYHRZQwwaZSpwbRvpbiJWwl4k0r05U1LeJspw85y1ol1OOrKulzaA4bh3OXa0A3PVnGxshw68OdzaHs6s3ZYbjhzubQ9nVm7LDccO4w7WgO46s52FkGXXh5xhgbRtpcdWRtTm0AyxPDyrqS8T5HTlfAvEulOIlTS1gSpyKRw46LuEFEljk2iTU3EuoYYpgVODYEqcikmDe95gtEljk2UFjgUihRjinQOKZSpwbq7LsaE/2teuleulGf6Wmdm3N1UscCkQIOMcJj8qOM/HRGM/NIEx+PGPN+loknf24P1WD9e0Ejakm/TcSzBRk08he4BOwpYDQiQUABsLkA7ijEhpoDRBG4ukhSlYMMjhmYKMmncubpCTvQAXYdEgNuKeEja6OUNKwYZHCyPrN44gvVkiDXjfQeEmf+bxR6evLHqGReF/54JjpBNEkkk2hTJz4MyYObAkEEUp1AHgZ22WwGSBQAUAeCQGBFEYJFoG3XgXOXNoF+SfDnX5Bshw44BjhSbxDCDw5RlDdTlQfPl7DcDAA8MjIIvF2Dz5uyw3Hinc2h7P8ASD//xAAUEQEAAAAAAAAAAAAAAAAAAACQ/9oACAECAQE/AEQ//8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAwEBPwBEP//Z';
